### ISSUE TITLE
[Joomla 4.0 backend template] Edit Article Layout

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/40-backend-template#418]
So this is the proposal for the Article Edit View.

Just in this view the tabs are at the bottom, the focus should be at the contents and many tabs can follow with custom fields so it's good to think affront how to add more tabs then the viewport is able to show in a row. A possibility could be to add a double angle icon left and right to switch through the tabs in the moment they would break.

Also attached a mobile example.

Any ideas are welcome and i can provide the sketch file for those that want to contribute to the design.

1) Create Article

![joomla4-edit-article](https://user-images.githubusercontent.com/828371/40282536-30ed7a78-5c71-11e8-8f6c-e0d42caec8df.png)

2) Save Actions
![joomla4-edit-article-save-actions](https://user-images.githubusercontent.com/828371/40282586-e5671d06-5c71-11e8-9d99-4a612958cd0f.png)

3) Inline Editing
![joomla4-edit-article-inline-editing](https://user-images.githubusercontent.com/828371/40282579-d2002ac8-5c71-11e8-8b04-a8e7fe231424.png)
![joomla4-edit-article-inline-editing copy](https://user-images.githubusercontent.com/828371/40282580-d43cd638-5c71-11e8-8c03-ce6d890dfcbc.png)

4) Image Inline Editing and contextual change of the Editor Buttons
![joomla4-edit-article-media-support](https://user-images.githubusercontent.com/828371/40282596-0754dee4-5c72-11e8-8444-84cc00337187.png)

5) Example for the images and Links Tab
![joomla4-edit-article-image-options](https://user-images.githubusercontent.com/828371/40282552-614c3588-5c71-11e8-938f-ed9ef7b5e4c6.png)

6) Saved Dialog inside the input
![joomla4-edit-article-3](https://user-images.githubusercontent.com/828371/40282550-5dd44fc6-5c71-11e8-8315-ffbc9506dca4.png)

**Comment by dgrammatiko** [comment]
> A possibility could be to add a double angle icon left and right to switch through the tabs in the moment they would break.

New tabs will never break, as if the viewport gets narrower they collapse to accordion

My question here will be:

Why tabs? It's a known antipattern for forms (we should never hide form elements)

**Comment by coolcat-creations** [comment]
@dgrammatiko Which other solution would you suggest? 
Please keep in mind Custom Fields Tabs and on...

**Comment by brianteeman** [comment]
1. i dont believe we can ever reduce the number of fields to the point that it is not overwhelming on a single screen

2. accessibility. tabs at the bottom can be done if there is a "jump to" link

3, accessibility. putting all the fields on a single form would mean you had to press the tabkey through a large number of fields to find the one you want, as opposed to "jumping to" a tab and then pressing the tabkey through a limited number of fields

**Comment by dgrammatiko** [comment]
> putting all the fields on a single form would mean you had to press the tabkey through a large number of fields to find the one you want

Depends what we consider data field, (I'm do not consider the stupid switches data entry fields), also last time I checked wp there is one page full of fields for the page/post. So someone got it wrong here, either we or they...

**Comment by brianteeman** [comment]
joomla is not wordpress

**Comment by mbabker** [comment]
WordPress doesn't have 100 options on the page/post editor like articles do.

**Comment by coolcat-creations** [comment]
We discussed every single bit of that design for so long and with so many...
Before the JCM Article was published we even agreed on it.

Please lets focus on -> Yes -> improvement 
but -> No -> changing everything from scratch again

**Comment by dgrammatiko** [comment]
> WordPress doesn't have 100 options on the page/post editor like articles do.

And exactly this is our problem and what I'm trying to highlight here. On the data entry form we also include the ACL and the output control. It's obviously that we're doing it wrong

**Comment by mbabker** [comment]
And it's not a fix to be made by slapping a new coat of paint (template) on the admin UI.  A lot of code and workflow adjustments involved here...

**Comment by dgrammatiko** [comment]
We do have a GSOC for the overrides, so all we have to fix ourselves is the ACL layer, or not?

**Comment by ciar4n** [comment]
@coolcat-creations Thank you for posting

Regarding the tabs, is there any benefit to placing the tabs at the bottom. Honestly I am failing to see any good reason for it. One issue I have with it is that it means users have to scroll to navigate to the majority of available options for this view.

**Comment by mbabker** [comment]
Nope.

You start moving params out of the backend forms, you have to pull those out of the layouts, pull the param handling/merging out of the code that handles that (i.e. when you're merging menu item params with article params on various views), etc.

It's documenting the ever loving crap out of all of this because you're basically going to start telling a lot of people they're going to have to make more use of layout overrides.  They're going to have to get smart in our PHP API, because some of the things you can do in the UI with options right now can affect a small subset of items; leaving this all to layouts means if you want an exception for a couple items you either hardcode ID exemption rules in your layouts or you build alternate layouts (and have to learn that feature to do it right).

Removing the stuff from the UI is just one small aspect of pulling options out of core.

**Comment by mbabker** [comment]
err, my comment was to @dgrammatiko, didn't see the other post come in 😉

**Comment by brianteeman** [comment]
and what would you do with upgraded sites?

**Comment by coolcat-creations** [comment]
@ciar4n The Tabs should be fixed at the bottom. There were some people suggesting to make the most important - the editorpanel - as far at the top as possible. So you don't have to scroll down towards the editorwindow on each article edit. You rather switch the tabs not that often, then editing an article.
I tried with different approaches and at JCW17 we made tests in a small team and that was the result.

**Comment by ciar4n** [comment]
When I get the chance I'll create the PR and see how it works... admittedly I am still not convinced but willing to give it a try :)

**Comment by dgrammatiko** [comment]
> and what would you do with upgraded sites?

well if we can't handle this, farming has been always a good alternative.

But anyways there is not strong will to move forward for J4, so I'll stop here. I'll back up @ciar4n for the tabs

**Comment by coolcat-creations** [comment]
@dgrammatiko Great! What will you need for the contextual change of the Editor Buttons ? (Since it was your idea)  ;-)

**Comment by dgrammatiko** [comment]
@coolcat-creations keep it hold for the moment, @brianteeman already proposed the new version of CK and also we were discussing the possibility to go to a newer editor with better UX, better pluggability and drop completely the iframe old tinyMCE

**Comment by dgrammatiko** [comment]
@coolcat-creations but even if that won't happen due to workload, I can easily make a PR with a custom element to get tinyMCE with inline theme (which has the behaviour we need, only thing is we need to plug our xtd-buttons): https://www.tinymce.com/docs/demo/inlite/

**Comment by dgrammatiko** [comment]
@brianteeman it shouldn't be a major problem, we have ES6-Es5 code for the custom elements so we can beef up our building tools and make 2 versions of CK and deliver the correct one depending on the client capabilities (also provide missing polyfills). We're already doing this with ce's

**Comment by micker** [comment]
I like this design... For me if i can say anything is the position for plugin button like module ect... I think we need to put it later this button are less important than content...
Maybe After description or in dropdown to be more compact
For me button need to be arranged in order of importance (most uses)
What do you think ?

**Comment by mbabker** [comment]
> For me button need to be arranged in order of importance (most uses)
> What do you think ?

That's too subjective.  Your workflow is different from mine which is different from everyone else's in this thread (I essentially don't use the WYSIWYG editors except to validate my markup isn't completely broken, others write in them like they're in a Google Docs or MS Word style editor).

Also, the editor button plugins are fully controlled by the plugin ordering, so you can customize at least that aspect of things to your liking.

**Comment by dgrammatiko** [comment]
@coolcat-creations why were are separate xtd-buttons? I mean I already concentrated that space to one dropdown.
So in that sense with a little tweaking of the tinyMCE template you get almost what you need:
![screen shot 2018-05-21 at 21 36 34](https://user-images.githubusercontent.com/3889375/40326399-616c62b2-5d3f-11e8-9844-01625e524699.png)

Also I tried to unify the xtd-buttons to the upper part of the editors (for all joomla editors) but brian and charlie was against it and I'm sick and tired fighting over obvious things...

**Comment by coolcat-creations** [comment]
> @coolcat-creations why were are separate xtd-buttons? I mean I already concentrated that space to one dropdown.
So in that sense with a little tweaking of the tinyMCE template you get almost what you need:

I can't install the current staging as posted 2 times ;) i have no idea about the current state.

**Comment by micker** [comment]
@dgrammatiko @mbabker sorry but its not realy subjective
think about end-user not joomla pro
if you create an article did you insert module or menu-link before adding text ?? 
for important option like bouton editor i am agree but for less used button we can win some place and having a better ux for first user impression 
the question the ordering of content is important about user apprehension ... create a joomla content is for integrator skill or author skill ?
it a detail but interesting to keep a little time one it for a better finition

**Comment by dgrammatiko** [comment]
@micker unless you haven't realised Joomla's tinyMCE (default core editor) has the xtd buttons **inside** the tinyMCE toolbar since 2014-15. I did that part after JAB Prague as it was decided that this was one of the easy UX improvements for J4, but we managed to get it in J3. So I'm not even following why do we have to discuss about reverting this...

**Comment by mbabker** [comment]
> for important option like bouton editor i am agree but for less used button we can win some place and having a better ux for first user impression

So you're suggesting to create a massively subjective set of two toolbars (one being the editor's "native" toolbar and one being the Joomla context specific buttons) instead of having a consistent UX with one toolbar?

> the question the ordering of content is important about user apprehension ... create a joomla content is for integrator skill or author skill ?
> it a detail but interesting to keep a little time one it for a better finition

By this argument tools like Microsoft Office or Google Drive have it wrong having the toolbar before the content workspace.

**Comment by micker** [comment]
ok i respect this no problem it's a details lol
thanks for time reply !
